# Generated by Django 5.1.7 on 2025-04-02 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
        ('transactions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'book', 'is_returned')},
        ),
    ]
